version: "3.9"

services:
  chatapi:
    build: .
    ports:
      - "8080:8000"
    links:
      - mysql8

  mysql8:
    image: mysql:8.0.42-oracle
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Isql1706

