# MySQL Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.42-oracle
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "JeR0204&&T411erBD"
        - name: MYSQL_DATABASE
          value: "chatdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persisten-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persisten-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
# FastAPI Deployment y Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server-deployment
  labels:
    app: fastapi-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - name: fastapi-server
        image: jeshuarocha/fastapi-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "JeR0204&&T411erBD"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: "chatdb"
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: LOG_LEVEL
          value: DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    app: fastapi-server
