apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server
  template:
    metadata:
      labels:
        app: fastapi-server
    spec:
      containers:
      - name: fastapi-server
        image: jeshuarocha/red_api:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mysql://root:JeR0204&&T411erBD@localhost:3306/chatdb"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "JeR0204&&T411erBD"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fastapi-server