name: Python_Red_API

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: JeR0204&&T411erBD
          MYSQL_DATABASE: chatdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Probar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Instalar dependecias
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi httpx mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Esperar a que MySQL este listo
      run: sleep 20

    - name: Ejecutar pruebas
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/servidor_HTTP:$(pwd)
        pytest
