name: Python_Red_API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: check out the repo
      uses: actions/checkout@v4.2.2

    - name: login to dockerhub
      uses: docker/login-action@v3.4.0
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_REDES_API }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v6.16.0
      with:
       context: ./servidor_HTTP
       file: ./servidor_HTTP/Dockerfile
       push: true
       tags: jeshuarocha/red_api:latest
      
