name: Python_Red_API

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
  
    runs-on: ubuntu-latest

    steps:
    - name: check out the repo
      uses: actions/checkout@v4.2.2

    - name: Probar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Instalar dependecias
      run: |
        python -m pip install --upgrade pip
        pip install fastapi httpx mock coverage pytest-cov mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Ejecutar pruebas
      run: |
        export PYTHONPATH=$PYTHONPATH:./servidor_HTTP
        coverage run -m pytest -v -s

    - name: Generar un reporte Coverage
      run: |
        coverage report -m        
  
  docker:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: login to dockerhub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_REDES_API }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v6.16.0
      with:
        context: ./servidor_HTTP
        file: ./servidor_HTTP/Dockerfile
        push: true
        tags: jeshuarocha/red_api:latest
