name: Python_Red_API

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: check out the repo
      uses: actions/checkout@v4.2.2

    - name: login to dockerhub
      uses: docker/login-action@v3.4.0
      with:
        python-version: "3.12.7"

    - name: Instalar dependecias
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi httpx mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Esperar a que MySQL este listo
      run: sleep 20

    - name: Ejecutar pruebas
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/servidor_HTTP:$(pwd)
        pytest
